### ISSUE TITLE
Switch to CBA facewear randomization

### ISSUE THREAD

**Issue by Kresky** [Theseus-Aegis/Units#23]
Title, with CBA having facewear randomization, our own one in TACU is redundant (they're more or less the same script, but may as well use CBA. Switching is easy enough anyway)
https://github.com/CBATeam/CBA_A3/wiki/Facewear-Randomization

**Comment by jonpas** [comment]
Just rename config entry to `CBA_facewearList[]` and you should be good. :)

**Comment by Kresky** [comment]
Yea, well that and replace `"None"` with `""` I believe as well.

**Comment by jonpas** [comment]
Both are supported just in case (but I recommend the change).
