### ISSUE TITLE
New Faction: Triads

### ISSUE THREAD

**Issue by Kresky** [Theseus-Aegis/Units#48]
Issue for myself so I don't forget stuffs.

When talking with Tyrone about the Cartel faction, we both agreed on the idea of a Asian cartel/triad as an idea (like cartels, they're worldwide, however a "mexican" cartel is hard to pull off given we have no identities in the game for it really. We do have asian faces and voicelines however, so that's a nice base to start with + it feels a bit unique).

Will do some poking about the internet looking up some Chinese Triads for inspiration.

Things that would need to be done:
- Need to reskin faces/arms (asian inspired tattoos, like dragons or whatever. Possibly the triad's logo if we can come up with something).
- Potential reskin of some civilian clothing for the low level gang members.
- Reskin of uniforms/vests for higher level members (spray painted logo on vests for example).
- Reskin of vehicles (again, spray painted logo's).
- Tiered units (low level, shit gear. Medium level is okay gear. High tier is sorta paramilitary kinda or something, good gear. Also a "boss/leader" sub category using those fancy pancy suits and what not from CUP).

Will likely just make it as a new faction instead of overwriting Cartel one. Can always easily delete it if we end up not wanting it.

**Comment by jonpas** [comment]
Katanas?
